# Задача 2. Я-профессионал. Отборочный тур. Машинное обучение.


Есть различные данные о полупроводниках: их химических состав, какие-то различные характеристики. Необходимо определить критическую температуру для этих полупроводников.
- formula_train.csv - тренировочные данные, файл содержит химический состав для каждого полупроводника
- train.csv - тренировочные данные, различные характеристики полупроводника
- formula_test.csv, test.csv - аналогично тестовые данные

In [48]:
import pandas as pd

formula_test = pd.read_csv("formula_test.csv")
formula_train = pd.read_csv("formula_train.csv")

test = pd.read_csv("test.csv")
train = pd.read_csv("train.csv")

formula_train.loc[0:10]

,H,He,Li,Be,B,C,N,O,F,Ne,...,Au,Hg,Tl,Pb,Bi,Po,At,Rn,critical_temp,material
0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,21.50,Eu1Fe1.5Ru0.5As2
1,0.0,0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0,...,0.0,0.0,0.0,0.0,2.0,0,0,0,62.00,Bi2Sr2Ca1Cu2O8
2,0.0,0,0.0,0.0,0.0,0.0,0.3,0.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,0.29,N0.3S0.7
3,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,19.50,Ba1Fe1.9Co0.1As2
4,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,5.36,Rh17S15
5,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,2.12,Ge2Rh3
6,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,1.95,Ti0.5Nb0.25Sb0.25
7,0.0,0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0,...,0.0,0.5,0.5,0.0,0.0,0,0,0,134.00,Tl0.5Hg0.5Ba2Ca2Cu3O8
8,0.0,0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,30.00,Mg0.97Fe0.03B2
9,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,...,0.0,0.0,0.0,1.4,0.0,0,0,0,52.00,Pb1.4Sr4Y1.2Ca0.8Cu4.6O
10,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,2.60,La7Rh3

In [49]:
train.head()

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature73,feature74,feature75,feature76,feature77,feature78,feature79,feature80,feature81,critical_temperature
0,4,95.950150,87.221940,89.534122,81.423258,1.317590,1.301059,96.1190,20.285800,36.105357,...,4.10,4.053600,3.944244,1.339718,1.245504,3,1.400000,1.299038,1.135782,21.50
1,5,83.244760,59.224400,59.506081,36.126175,1.311510,1.372050,192.9810,25.192187,67.233835,...,2.40,2.402249,2.259897,1.519383,1.365077,3,0.933333,1.200000,1.019804,62.00
2,2,23.035850,26.647510,21.192566,25.010514,0.614232,0.435817,18.0583,18.243490,9.029150,...,5.10,4.242641,4.873514,0.636514,0.465999,3,3.300000,1.500000,1.374773,0.29
3,4,81.756699,79.833804,76.282833,75.275775,1.312596,1.149324,81.4820,28.789976,32.890369,...,3.62,3.309751,3.413039,1.333736,1.019322,3,1.920000,1.118034,1.198165,19.50
4,2,67.485250,69.699016,57.442709,59.574464,0.548263,0.521345,70.8405,39.638078,35.420250,...,6.00,6.000000,6.000000,0.693147,0.691193,0,0.375000,0.000000,0.000000,5.36

In [50]:
formula_test.head()

,H,He,Li,Be,B,C,N,O,F,Ne,...,Pt,Au,Hg,Tl,Pb,Bi,Po,At,Rn,material
0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,...,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0,La1Ba2Cu2.94Fe0.06O
1,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0.08,0.0,0.0,0.0,0.0,0.0,0,0,0,Sr1Pd1.92Pt0.08Ge2
2,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0,Ba1Fe1.55Ru0.45As2
3,0.0,0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0,...,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0,Y1Ba2Cu2.97Fe0.03O7
4,0.0,0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0,...,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0,Pr1.85Ce0.15Cu1O4

In [51]:
test.head()

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature72,feature73,feature74,feature75,feature76,feature77,feature78,feature79,feature80,feature81
0,5,82.324574,88.533544,64.110667,72.640059,1.418486,1.179961,122.90607,38.757614,48.331141,...,2.4,2.151429,2.352158,2.126646,1.589027,1.361750,1,0.814286,0.489898,0.358466
1,4,115.438500,90.562624,107.211420,88.713057,1.308571,1.157701,122.45400,37.743936,47.516249,...,4.0,3.632000,3.722419,3.504866,1.320888,1.064083,4,1.504000,1.414214,0.853567
2,4,92.290900,83.842290,87.295606,79.318618,1.331889,1.300022,81.48200,20.872340,30.558629,...,4.0,3.870000,3.662842,3.611896,1.305096,1.193165,4,1.600000,1.581139,1.361286
3,5,72.324650,51.227894,58.637102,34.924853,1.444612,1.306314,121.32760,20.998358,40.053512,...,2.4,2.079231,2.352158,2.065294,1.589027,1.219461,1,1.070000,0.489898,0.270099
4,4,90.142263,58.462879,66.935044,36.272055,1.178649,1.019134,124.90825,34.237393,53.101375,...,3.0,2.571429,2.828427,2.438027,1.329661,1.083356,2,1.057143,1.000000,0.903508

# Исследование данных

1. Размерность данных?
2. Какая переменная целевая?
3. Есть ли категориальные переменные?
4. Есть ли пропуски?

In [52]:
print(formula_train.shape)
print(train.shape)
# 88+82-1-1-1=167

(17000, 88)
(17000, 82)

In [53]:
print(formula_test.shape)
print(test.shape)
# всего признаков 87+81-1 = 167
# material - строковая переменная, которую удалить и не использовать для анализа

(4263, 87)
(4263, 81)

In [54]:
tmp = train.isna().sum()
tmp.sum()

0

In [55]:
tmp = formula_train.isna().sum()
tmp.sum()

0

In [56]:
tmp = formula_test.isna().sum()
print(tmp.sum())
tmp = test.isna().sum()
print(tmp.sum())

# можно сделать вывод, что пропусков в наших данных нет

0
0

In [57]:
formula_train.dtypes

H                float64
He                 int64
Li               float64
Be               float64
B                float64
                  ...
Po                 int64
At                 int64
Rn                 int64
critical_temp    float64
material          object
Length: 88, dtype: object

In [58]:
train.dtypes

feature1                  int64
feature2                float64
feature3                float64
feature4                float64
feature5                float64
                         ...
feature78                 int64
feature79               float64
feature80               float64
feature81               float64
critical_temperature    float64
Length: 82, dtype: object

In [59]:
formula_test.dtypes

H           float64
He            int64
Li          float64
Be          float64
B           float64
             ...
Bi          float64
Po            int64
At            int64
Rn            int64
material     object
Length: 87, dtype: object

In [60]:
test.dtypes

feature1       int64
feature2     float64
feature3     float64
feature4     float64
feature5     float64
              ...
feature77    float64
feature78      int64
feature79    float64
feature80    float64
feature81    float64
Length: 81, dtype: object

# Подготовка данных

In [63]:
# объединим все признаки в один датафрейм
X_train_full = pd.concat([formula_train, train], axis=1)
X_train_full = X_train_full.drop(['material', 'critical_temperature', 'critical_temp'], axis=1)

print(X_train_full.head())
print(X_train_full.shape)

     H  He   Li   Be    B    C    N    O    F  Ne  ...  feature72  feature73  \
0  0.0   0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0  ...       4.25       4.10
1  0.0   0  0.0  0.0  0.0  0.0  0.0  8.0  0.0   0  ...       2.60       2.40
2  0.0   0  0.0  0.0  0.0  0.0  0.3  0.0  0.0   0  ...       4.50       5.10
3  0.0   0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0  ...       3.50       3.62
4  0.0   0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0  ...       6.00       6.00

   feature74  feature75  feature76  feature77  feature78  feature79  \
0   4.053600   3.944244   1.339718   1.245504          3   1.400000
1   2.402249   2.259897   1.519383   1.365077          3   0.933333
2   4.242641   4.873514   0.636514   0.465999          3   3.300000
3   3.309751   3.413039   1.333736   1.019322          3   1.920000
4   6.000000   6.000000   0.693147   0.691193          0   0.375000

   feature80  feature81
0   1.299038   1.135782
1   1.200000   1.019804
2   1.500000   1.374773
3   1.118034   1.198165
4   0.000000   0.000000

[5 rows x 167 columns]
(17000, 167)

In [64]:
# выделим вектор ответов для тренировочных данных
y_train_full = train['critical_temperature']
print(y_train_full.shape)

(17000,)

In [70]:
# проведем нормализацию данных
# StandartScaler() - стандартизация
# from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X_train_full)
X_train_full_norm = scaler.transform(X_train_full)
print(X_train_full_norm)

[[-0.06682301  0.         -0.09496725 ... -0.08495168  0.94652758
   1.00993367]
 [-0.06682301  0.         -0.09496725 ... -0.56101887  0.74234198
   0.75575738]
 [-0.06682301  0.         -0.09496725 ...  1.85332188  1.36084816
   1.53370522]
 ...
 [-0.06682301  0.         -0.09496725 ...  3.38353784 -1.73168274
  -1.47923968]
 [-0.06682301  0.         -0.09496725 ... -0.67492025 -0.83894597
  -0.88960789]
 [-0.06682301  0.         -0.09496725 ...  0.51244464  0.37083398
   1.14349705]]

In [71]:
# проделаем аналогичные действия для тестовых данных
X_full_test = pd.concat([formula_test, test], axis=1)
X_full_test = X_full_test.drop(['material'], axis=1)
print(X_full_test.shape)

# scaler = MinMaxScaler(feature_range=(0, 1))
# scaler.fit(X_full_test)
X_full_test_norm = scaler.transform(X_full_test)
print(X_full_test_norm)

(4263, 167)
[[-0.06682301  0.         -0.09496725 ... -0.68246458 -0.72166638
  -0.69362715]
 [-0.06682301  0.         -0.09496725 ...  0.0211433   1.18398335
   0.39143263]
 [-0.06682301  0.         -0.09496725 ...  0.11907712  1.52813105
   1.50414816]
 ...
 [-0.06682301  0.         -0.09496725 ...  0.28910111 -0.04832214
  -0.32648019]
 [-0.06682301  0.         -0.09496725 ...  0.65676764  1.29836634
   1.51602146]
 [-0.06682301  0.         -0.09496725 ...  0.91478942  0.83969305
   1.13674262]]

# Построение модели

Используем градиентный бустинг для решения данной задачи. 

Современные реализации градиентного бустинга над деревьями для языка Python:

- sklearn.ensemble. GradientBoostingRegressor / GradientBoostingClassifier
- XGBoost (eXtreme Gradient Boosting)
- LightGBM, Light Gradient Boosting Machine

Последние две существенно быстрее и лучше (по качеству)

In [34]:
# RandomForestClassifer - RandomForestRegressor
# SVC (support vecrot classifier) - SVR

# Accuracy, recall, preciosion - для классификации

# R2 score, MSE, MAE

In [72]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

X_train, X_test, y_train, y_test = train_test_split(X_train_full_norm, y_train_full, test_size=0.3, random_state=1)

gbr = GradientBoostingRegressor(random_state=1)
gbr.fit(X_train,y_train)

y_pred_gbr = gbr.predict(X_test)

print('R_2_score:', r2_score(y_test, y_pred_gbr))
print('mean_absolute_error:', mean_absolute_error(y_test, y_pred_gbr))
print('mean_squared_error:', mean_squared_error(y_test, y_pred_gbr))
# 87%

R_2_score: 0.864363619993128
mean_absolute_error: 8.323616108990302
mean_squared_error: 158.65569418345842

In [ ]:
# Используя GridSearchCV мы также можем подобрать лучшие параметры для GradientBoostingRegressor
n_estimators = [100, 500, 900, 1100, 1500]
learning_rate = [1, 0.5, 0.3, 0.2, 0.1]

# создадим сетку параметров
gbm_grid = {
    'n_estimators': n_estimators,
    'learning_rate': learning_rate}

gbm = GradientBoostingRegressor()
gbm_cv = GridSearchCV(gbm, param_grid = gbm_grid, cv = kf, scoring='r2')
gbm_cv.fit(X_train_full_norm, y_train_full)

C = gbm_cv.best_params_
print("Best params:", C)

In [ ]:
# проверим какая оценка получилась при лучших параметрах
X_train, X_test, y_train, y_test = train_test_split(X_train_full_norm, y_train_full, test_size=0.3, random_state=1)

gbm = GradientBoostingRegressor()
gbm.fit(X_train, y_train)
gbm_pred = gbm.predict(X_test)

print('R_2_score:', r2_score(y_test, gbr_pred))
print('mean_absolute_error:', mean_absolute_error(y_test, gbr_pred))
print('mean_squared_error:', mean_squared_error(y_test, gbr_pred))
# 92%

XGBoost — библиотека, реализующая методы градиентного бустинга. Ее производительность сделала данную библиотеку одним из лидеров в области машинного обучения.

XGBoost — алгоритм машинного обучения, основанный на дереве поиска решений и использующий фреймворк градиентного бустинга.

Подробнее о библиотеке:
https://xgboost.readthedocs.io/en/latest/python/python_api.html#module-xgboost.sklearn

In [73]:
from xgboost import XGBRegressor

X_train, X_test, y_train, y_test = train_test_split(X_train_full_norm, y_train_full, test_size=0.3, random_state=1)

xgb = XGBRegressor()
xgb.fit(X_train, y_train)
xgb_pred = xgb.predict(X_test)

print('R_2_score:', r2_score(y_test, xgb_pred))
print('mean_absolute_error:', mean_absolute_error(y_test, xgb_pred))
print('mean_squared_error:', mean_squared_error(y_test, xgb_pred))
# 86%

R_2_score: 0.9207936356245983
mean_absolute_error: 5.6967657954905375
mean_squared_error: 92.64874750484081

In [74]:
from sklearn.model_selection import KFold, GridSearchCV

kf = KFold(n_splits=5, shuffle=True, random_state=42)

xgb = XGBRegressor()

grid = {'n_estimators': [100, 300, 500], 'max_depth': [3, 5]}

xgb_cv = GridSearchCV(xgb, param_grid = grid, cv = kf, scoring='r2')
xgb_cv.fit(X_train_full_norm, y_train_full)

C = xgb_cv.best_params_
print("Best params:", C)
# > 15 минут

Best params: {'max_depth': 5, 'n_estimators': 500}

In [75]:
# проверим какая оценка получилась при лучших параметрах
X_train, X_test, y_train, y_test = train_test_split(X_train_full_norm, y_train_full, test_size=0.3, random_state=1)

xgb = XGBRegressor(max_depth = 5, n_estimators = 500)
xgb.fit(X_train, y_train)
xgb_pred = xgb.predict(X_test)

print('R_2_score:', r2_score(y_test, xgb_pred))
print('mean_absolute_error:', mean_absolute_error(y_test, xgb_pred))
print('mean_squared_error:', mean_squared_error(y_test, xgb_pred))
# 92%

R_2_score: 0.9214858305838748
mean_absolute_error: 5.454050461252275
mean_squared_error: 91.83907777044693

In [76]:
# предскажем ответы для тестовых данных

xgb_pred_on_test = xgb.predict(X_full_test_norm)

xgb_pred_on_test = pd.DataFrame(xgb_pred_on_test, columns=['critical_temp'])
xgb_pred_on_test = xgb_pred_on_test.reset_index()
xgb_pred_on_test

      index  critical_temp
0         0      63.974510
1         1       1.306749
2         2      18.803043
3         3      88.553093
4         4      19.749664
...     ...            ...
4258   4258      -0.151422
4259   4259      86.585426
4260   4260      33.889233
4261   4261      27.147018
4262   4262       7.217888

[4263 rows x 2 columns]

In [77]:
xgb_pred_on_test.to_csv('critical_temp_submit2.csv', index = False)