# Задача 2. Я-профессионал. Отборочный тур. Машинное обучение.


Есть различные данные о полупроводниках: их химических состав, какие-то различные характеристики. Необходимо определить критическую температуру для этих полупроводников.
- formula_train.csv - тренировочные данные, файл содержит химический состав для каждого полупроводника
- train.csv - тренировочные данные, различные характеристики полупроводника
- formula_test.csv, test.csv - аналогично тестовые данные

In [1]:
import pandas as pd

formula_test = pd.read_csv("formula_test.csv")
formula_train = pd.read_csv("formula_train.csv")

test = pd.read_csv("test.csv")
train = pd.read_csv("train.csv")

formula_train

,H,He,Li,Be,B,C,N,O,F,Ne,...,Au,Hg,Tl,Pb,Bi,Po,At,Rn,critical_temp,material
0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,21.500,Eu1Fe1.5Ru0.5As2
1,0.0,0,0.0,0.0,0.0,0.0,0.0,8.00,0.0,0,...,0.0,0.0,0.0,0.0,2.0,0,0,0,62.000,Bi2Sr2Ca1Cu2O8
2,0.0,0,0.0,0.0,0.0,0.0,0.3,0.00,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,0.290,N0.3S0.7
3,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,19.500,Ba1Fe1.9Co0.1As2
4,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,5.360,Rh17S15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16995,0.0,0,0.0,0.0,0.0,0.0,0.0,4.00,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,35.000,La2Cu1O4
16996,0.0,0,0.8,0.0,0.0,0.0,0.0,1.00,0.0,0,...,0.0,0.0,0.0,0.0,2.0,0,0,0,89.000,Bi2Sr2Ca1Cu1.2Li0.8O
16997,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,0.584,Os0.9Ru0.1
16998,0.0,0,0.0,0.0,0.0,0.0,0.0,6.73,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,45.000,Sm1Ba2Cu3O6.73
16999,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,13.500,Ba1Fe1.832Co0.15Mn0.018As2

In [2]:
train.head()

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature73,feature74,feature75,feature76,feature77,feature78,feature79,feature80,feature81,critical_temperature
0,4,95.950150,87.221940,89.534122,81.423258,1.317590,1.301059,96.1190,20.285800,36.105357,...,4.10,4.053600,3.944244,1.339718,1.245504,3,1.400000,1.299038,1.135782,21.50
1,5,83.244760,59.224400,59.506081,36.126175,1.311510,1.372050,192.9810,25.192187,67.233835,...,2.40,2.402249,2.259897,1.519383,1.365077,3,0.933333,1.200000,1.019804,62.00
2,2,23.035850,26.647510,21.192566,25.010514,0.614232,0.435817,18.0583,18.243490,9.029150,...,5.10,4.242641,4.873514,0.636514,0.465999,3,3.300000,1.500000,1.374773,0.29
3,4,81.756699,79.833804,76.282833,75.275775,1.312596,1.149324,81.4820,28.789976,32.890369,...,3.62,3.309751,3.413039,1.333736,1.019322,3,1.920000,1.118034,1.198165,19.50
4,2,67.485250,69.699016,57.442709,59.574464,0.548263,0.521345,70.8405,39.638078,35.420250,...,6.00,6.000000,6.000000,0.693147,0.691193,0,0.375000,0.000000,0.000000,5.36

In [3]:
formula_test.head()

,H,He,Li,Be,B,C,N,O,F,Ne,...,Pt,Au,Hg,Tl,Pb,Bi,Po,At,Rn,material
0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,...,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0,La1Ba2Cu2.94Fe0.06O
1,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0.08,0.0,0.0,0.0,0.0,0.0,0,0,0,Sr1Pd1.92Pt0.08Ge2
2,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0,Ba1Fe1.55Ru0.45As2
3,0.0,0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0,...,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0,Y1Ba2Cu2.97Fe0.03O7
4,0.0,0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0,...,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0,Pr1.85Ce0.15Cu1O4

In [4]:
test.head()

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature72,feature73,feature74,feature75,feature76,feature77,feature78,feature79,feature80,feature81
0,5,82.324574,88.533544,64.110667,72.640059,1.418486,1.179961,122.90607,38.757614,48.331141,...,2.4,2.151429,2.352158,2.126646,1.589027,1.361750,1,0.814286,0.489898,0.358466
1,4,115.438500,90.562624,107.211420,88.713057,1.308571,1.157701,122.45400,37.743936,47.516249,...,4.0,3.632000,3.722419,3.504866,1.320888,1.064083,4,1.504000,1.414214,0.853567
2,4,92.290900,83.842290,87.295606,79.318618,1.331889,1.300022,81.48200,20.872340,30.558629,...,4.0,3.870000,3.662842,3.611896,1.305096,1.193165,4,1.600000,1.581139,1.361286
3,5,72.324650,51.227894,58.637102,34.924853,1.444612,1.306314,121.32760,20.998358,40.053512,...,2.4,2.079231,2.352158,2.065294,1.589027,1.219461,1,1.070000,0.489898,0.270099
4,4,90.142263,58.462879,66.935044,36.272055,1.178649,1.019134,124.90825,34.237393,53.101375,...,3.0,2.571429,2.828427,2.438027,1.329661,1.083356,2,1.057143,1.000000,0.903508